services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      - "7000:9000"
      - "7001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KET: minio123
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123

    volumes:
      - minio_data:/data/minio
    command: 'minio server /data/minio --console-address ":9001"'
    restart: unless-stopped

volumes:
  minio_data: