spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/soosmart_facts_dev
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false



my:
  secretkey: KAToeM8HWTPndcVZkace0kiVOkyAWipdsVnHKv955lY=

file:
  storage:
    provider: minio
    local:
      # Chemin de base pour le stockage local
      base-path: ${FILE_BASE_PATH:./uploads}
      # ou pour Windows: C:\app\uploads
      # ou pour d√©veloppement: ./uploads
    max-size: 104857600
    allowed-types: jpg,jpeg,png,pdf,doc,docx

# Configuration MinIO
minio:
  endpoint: http://127.0.0.1:9000/
  access-key: ypbvvTjBPOFzkeKfyDXn
  secret-key: bv6yejmY67SvkxnPiDO0p3YUj6eI66z2JAfblecD
  bucket-name: soosmart