spring:
  application:
    name: facts

  profiles:
    active: dev

server:
  port: 4000
  servlet:
    context-path: /api
#    multithreaded: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      max-swallow-size: 10MB
      resole-lazily: true
